### PR TITLE
Backport stderr

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by ancorgs** [comment]
Shouldn't we also mention bnc#956265 in the changelog?

**Comment by jreidinger** [comment]
@ancorgs I worry that if I mention it, then BS start complaining, that it is not fixed in SP1 and SP2 and I do not want to change changes just due to it.

**Comment by jreidinger** [comment]
basically rule is everything from older have to be fixed in newer, so mentioning it can cause panic, that it is not fixed in newer

**Comment by ancorgs** [comment]
Ok. LGTM then

**Comment by jreidinger** [comment]
thanks

**Pull request merged**
